# Generated by Django 3.0.10 on 2020-09-27 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatrooms', '0002_auto_20200927_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='Description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='Name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
