# Generated by Django 3.0.10 on 2020-09-27 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatrooms', '0003_auto_20200927_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatroom',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='chatroom',
            old_name='Name',
            new_name='name',
        ),
    ]
