# Generated by Django 3.0.10 on 2020-09-28 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatrooms', '0006_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sent',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
